# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Deploy to shinyapps.io

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to shinyapps
    environment: production
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependency
        run: |
          install.packages(c("shiny", "leaflet", "shinydashboard", "ggplot2", "dplyr", "randomForest", "rpart", "nnet", "caret", "mlr", "DT", "DALEX", "shinythemes", "pROC"), type = "binary")
      - name: shinyapps deploy
        run: |
             rsconnect::setAccountInfo(name= 'pbalewski', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')
             rsconnect::deployApp(appName = 'Dashboard',account = 'marcinkapiszewski156048', server = 'shinyapps.io', forceUpdate = TRUE)
        shell: Rscript {0}
